#!/bin/bash

# =================================================================
# DOCKERFILE OPTIMIZATION SCRIPT
# Automatically optimizes Dockerfile for size and performance
# =================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

DOCKERFILE_PATH=${1:-"./apps/api/Dockerfile"}
OUTPUT_PATH=${2:-"${DOCKERFILE_PATH}.optimized"}

print_usage() {
    echo "Usage: $0 [DOCKERFILE_PATH] [OUTPUT_PATH]"
    echo ""
    echo "Optimizes a Dockerfile for size and performance"
    echo ""
    echo "Parameters:"
    echo "  DOCKERFILE_PATH    Path to input Dockerfile (default: ./apps/api/Dockerfile)"
    echo "  OUTPUT_PATH        Path to output optimized Dockerfile (default: input + .optimized)"
}

check_prerequisites() {
    if [[ ! -f "$DOCKERFILE_PATH" ]]; then
        log_error "Dockerfile not found: $DOCKERFILE_PATH"
        exit 1
    fi
    
    log_info "Optimizing: $DOCKERFILE_PATH"
    log_info "Output: $OUTPUT_PATH"
}

analyze_dockerfile() {
    log_info "Analyzing current Dockerfile..."
    
    local layers=$(grep -c "^FROM\|^RUN\|^COPY\|^ADD" "$DOCKERFILE_PATH")
    local run_commands=$(grep -c "^RUN" "$DOCKERFILE_PATH")
    local copy_commands=$(grep -c "^COPY\|^ADD" "$DOCKERFILE_PATH")
    
    echo "Current stats:"
    echo "  - Total instruction layers: $layers"
    echo "  - RUN commands: $run_commands"
    echo "  - COPY/ADD commands: $copy_commands"
    
    # Check for common anti-patterns
    log_info "Checking for optimization opportunities..."
    
    if grep -q "npm install.*&&.*npm cache clean" "$DOCKERFILE_PATH"; then
        log_success "✓ Found npm cache cleanup"
    else
        log_warning "⚠ Missing npm cache cleanup"
    fi
    
    if grep -q "apk.*--no-cache" "$DOCKERFILE_PATH"; then
        log_success "✓ Found apk --no-cache usage"
    elif grep -q "apk add" "$DOCKERFILE_PATH"; then
        log_warning "⚠ apk commands without --no-cache"
    fi
    
    if grep -q "rm -rf.*tmp\|rm -rf.*cache" "$DOCKERFILE_PATH"; then
        log_success "✓ Found temp file cleanup"
    else
        log_warning "⚠ Missing temp file cleanup"
    fi
}

optimize_dockerfile() {
    log_info "Creating optimized Dockerfile..."
    
    # Create optimized multi-stage Dockerfile
    cat > "$OUTPUT_PATH" << 'EOF'
# =================================================================
# OPTIMIZED MULTI-STAGE DOCKERFILE
# Generated by optimize-dockerfile.sh
# =================================================================

# Base stage with common dependencies
FROM node:20-alpine AS base
RUN apk add --no-cache \
    dumb-init \
    tini \
    curl \
    && rm -rf /var/cache/apk/*

WORKDIR /app
RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nestjs

# Dependencies stage
FROM base AS deps
RUN apk add --no-cache \
    build-base \
    python3 \
    make \
    g++ \
    && rm -rf /var/cache/apk/*

COPY package*.json pnpm-lock.yaml ./
RUN npm install -g pnpm@latest

# Install all dependencies
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

# Builder stage
FROM deps AS builder
COPY . .
RUN pnpm build

# Production dependencies stage
FROM base AS prod-deps
RUN apk add --no-cache \
    build-base \
    python3 \
    make \
    g++ \
    && rm -rf /var/cache/apk/*

COPY package*.json pnpm-lock.yaml ./
RUN npm install -g pnpm@latest

# Install only production dependencies
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile --prod

# Clean up node_modules
RUN find ./node_modules -name "*.md" -delete \
    && find ./node_modules -name "*.txt" -delete \
    && find ./node_modules -name "LICENSE*" -delete \
    && find ./node_modules -name "CHANGELOG*" -delete \
    && find ./node_modules -name "*.map" -delete \
    && find ./node_modules -type d -name "test" -exec rm -rf {} + 2>/dev/null || true \
    && find ./node_modules -type d -name "tests" -exec rm -rf {} + 2>/dev/null || true \
    && find ./node_modules -type d -name "__tests__" -exec rm -rf {} + 2>/dev/null || true

# Remove build dependencies
RUN apk del build-base python3 make g++ \
    && rm -rf /var/cache/apk/*

# Runtime stage
FROM node:20-alpine AS runtime

# Install runtime dependencies
RUN apk add --no-cache \
    dumb-init \
    tini \
    curl \
    && rm -rf /var/cache/apk/* \
    && rm -rf /tmp/* \
    && rm -rf /var/tmp/*

# Create non-root user
RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nestjs

WORKDIR /app

# Copy production dependencies and built application
COPY --from=prod-deps --chown=nestjs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nestjs:nodejs /app/dist ./dist
COPY --from=builder --chown=nestjs:nodejs /app/package.json ./

# Set up directories
RUN mkdir -p /app/uploads \
    && chown -R nestjs:nodejs /app \
    && chmod -R 755 /app

# Environment
ENV NODE_ENV=production
ENV PORT=3000

# Security
USER nestjs

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:3000/health || exit 1

# Use tini for proper signal handling
ENTRYPOINT ["tini", "--"]

# Start application
CMD ["node", "dist/main.js"]

# Metadata
LABEL maintainer="Rockwell Team"
LABEL version="1.0.0"
LABEL description="Optimized Rockwell API"
EOF

    log_success "Optimized Dockerfile created: $OUTPUT_PATH"
}

compare_dockerfiles() {
    log_info "Comparing original and optimized Dockerfiles..."
    
    local original_size=$(wc -l < "$DOCKERFILE_PATH")
    local optimized_size=$(wc -l < "$OUTPUT_PATH")
    
    echo "File sizes:"
    echo "  - Original: $original_size lines"
    echo "  - Optimized: $optimized_size lines"
    
    # Count stages
    local original_stages=$(grep -c "^FROM.*AS" "$DOCKERFILE_PATH" || echo "1")
    local optimized_stages=$(grep -c "^FROM.*AS" "$OUTPUT_PATH")
    
    echo "Build stages:"
    echo "  - Original: $original_stages stages"
    echo "  - Optimized: $optimized_stages stages"
}

generate_build_commands() {
    log_info "Generating optimized build commands..."
    
    local build_script="build-optimized.sh"
    
    cat > "$build_script" << EOF
#!/bin/bash

# Build optimized Docker image
set -e

IMAGE_NAME=\${1:-"rockwell/api"}
TAG=\${2:-"optimized"}

echo "Building optimized image: \$IMAGE_NAME:\$TAG"

# Use BuildKit for better caching and optimization
export DOCKER_BUILDKIT=1

# Build with cache mounts and multi-stage optimization
docker build \\
    --file "$OUTPUT_PATH" \\
    --tag "\$IMAGE_NAME:\$TAG" \\
    --target runtime \\
    --build-arg BUILDKIT_INLINE_CACHE=1 \\
    --progress=plain \\
    .

echo "Build completed: \$IMAGE_NAME:\$TAG"

# Show image size
echo "Image size:"
docker images "\$IMAGE_NAME:\$TAG" --format "table {{.Repository}}\\t{{.Tag}}\\t{{.Size}}"
EOF

    chmod +x "$build_script"
    log_success "Build script created: $build_script"
}

provide_recommendations() {
    log_info "Additional optimization recommendations:"
    
    echo ""
    echo "1. Use the optimized Dockerfile:"
    echo "   cp $OUTPUT_PATH $DOCKERFILE_PATH"
    echo ""
    
    echo "2. Build with BuildKit for better performance:"
    echo "   export DOCKER_BUILDKIT=1"
    echo "   docker build -f $OUTPUT_PATH -t rockwell/api:optimized ."
    echo ""
    
    echo "3. Use multi-platform builds:"
    echo "   docker buildx build --platform linux/amd64,linux/arm64 -t rockwell/api:optimized ."
    echo ""
    
    echo "4. Consider these additional optimizations:"
    echo "   • Use distroless images for even smaller size"
    echo "   • Implement layer caching in CI/CD"
    echo "   • Use Docker image scanning for security"
    echo "   • Consider using docker-slim for further optimization"
    echo ""
    
    echo "5. Monitor image size over time:"
    echo "   docker images --format 'table {{.Repository}}\\t{{.Tag}}\\t{{.Size}}\\t{{.CreatedAt}}'"
}

main() {
    if [[ "$1" == "--help" || "$1" == "-h" ]]; then
        print_usage
        exit 0
    fi
    
    log_info "Starting Dockerfile optimization..."
    
    check_prerequisites
    analyze_dockerfile
    optimize_dockerfile
    compare_dockerfiles
    generate_build_commands
    provide_recommendations
    
    log_success "Dockerfile optimization completed!"
    log_info "Review the optimized Dockerfile at: $OUTPUT_PATH"
}

main "$@"