onlyBuiltDependencies:
  - '@contrast/fn-inspect'
  - '@nestjs/core'
  - '@newrelic/fn-inspect'
  - '@newrelic/native-metrics'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - protobufjs
  - unrs-resolver
